### ISSUE TITLE
Deleting Required Sections

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/InstantDep#50] opened 2019-01-11 21:26 UTC
If you go to the sample page, which is a required field, you have the option to hit delete. Upon doing so it removes the page from the sidebar menu and you cannot access it from the next/previous category buttons either. Immediately after deleting the selection the following appears "No matching saveframes found in this entry. Click here to return to a category that exists." This can be done for any page that has the delete option at the top and I have yet to find a way to recover the deleted sections. I think these pages should be like the Citations and Molecular entity page where the first block does not have a delete option, but subsequent ones do.

**Comment by rsiegl** [comment] 2019-01-11 21:30
This also removes the deleted sections from the downloaded and/or completed entry as you could assume.

**Comment by jonwedell** [comment] 2019-01-11 22:13
We discussed this in person, but to make a record for posterity:

This is actually defined in the dictionary: some saveframes are mandatory (and therefore cannot be deleted) and others are not. In theory, you could have a theoretical experiment with no sample. Therefore all the behavior to hide deleted saveframes is proper and on purpose.

What is needed though, is a way to restore accidentally-deleted saveframes to prevent users from accidentally permanently mangling their entry. I will implement a menu to restore a given deleted saveframe like we discussed.

**Comment by jonwedell** [comment] 2019-02-04 19:36
Duplicate of #53.

**Closed by jonwedell** 2019-02-04 19:36 UTC
